### ISSUE TITLE
Publish  0.4.1 to hex.pm?

### ISSUE THREAD

**Issue by sg2342** [knusbaum/provider_asn1#20]
It would be great if you published version 0.4.1 of this plugin to hex.pm. The `compile_order` feature is really helpful.

**Comment by NelsonVides** [comment]
@knusbaum Can we follow up on this? Can I help you in any way to publish this to hex? 🙏🏽

**Comment by NelsonVides** [comment]
I've gotten ownership in hex and I've published all the newer versions as they are in here: https://hex.pm/packages/provider_asn1.

@sebastiw it seems to me like you're the only current maintainer here, isn't it? Let me know if you want to sync on this package's maintenance :)

This issue can be closed now, but I have no admin rights to close it.

**Comment by sebastiw** [comment]
Thank you for your help!

**Comment by knusbaum** [comment]
@NelsonVides @sebastiw 

Sorry for the long absence. These days I do not have time to continue maintaining this package, as much as I would like to.

@sebastiw has been the primary maintainer here for some time, but did not have access to the hex repository.
@NelsonVides I see you have managed to take control of the hex package. I would request you also give @sebastiw access to it since he is the primary maintainer of this repository.

I thank you both sincerely for keeping this package going while I have not been able to give it attention.

**Comment by NelsonVides** [comment]
@knusbaum that's great, thank you for taking the time to answer! @sebastiw what is your hex account? I'll happily share the publishing rights. @knusbaum, might I ask you to add me as a maintainer here too so that I can help out with code as well?

Thanks to you both!

**Comment by knusbaum** [comment]
@NelsonVides Under normal circumstances, I would be a little hesitant to add someone as a maintainer who has not contributed yet to the code.

However, I took a look at your profile and see that you have regular, high-quality pull requests to large erlang projects going back years, so I have confidence that you will be a good maintainer here.

I spoke with @sebastiw and he enthusiastically agreed to add you as a maintainer as well. Welcome aboard.

**Comment by sebastiw** [comment]
@NelsonVides it's [sebastiw](https://hex.pm/users/sebastiw) there as well :+1:
Thank you

**Comment by NelsonVides** [comment]
@knusbaum thank you very much for your trust :)

@sebastiw, added you as an owner in hex!
